define(function () {
    return {
        'CAN': {
            'name': 'Canada',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.2224, 2.244, 2.7336, 0.0],
            'overallConsumptionBothSexes': 10.20,
            'bingeDrinkingMenProportion': 26.7,
            'bingeDrinkingWomenProportion': 7.6,
            'abstainersPast12MonthsProportion': 22.9,
            'overallRank': '40th heaviest',
            'overallConsumptionMen': 15.10,
            'overallConsumptionWomen': 5.50
        },
        'STP': {
            'name': 'Sao Tome and Principe',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.6685, 4.2742, 1.1573, 0.0],
            'overallConsumptionBothSexes': 7.10,
            'bingeDrinkingMenProportion': 9.3,
            'bingeDrinkingWomenProportion': 1.8,
            'abstainersPast12MonthsProportion': 61.9,
            'overallRank': 'joint 73rd heaviest',
            'overallConsumptionMen': 11.50,
            'overallConsumptionWomen': 2.90
        },
        'TKM': {
            'name': 'Turkmenistan',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.6622, 1.1223, 2.5112, 0.0],
            'overallConsumptionBothSexes': 4.30,
            'bingeDrinkingMenProportion': 23.5,
            'bingeDrinkingWomenProportion': 0.4,
            'abstainersPast12MonthsProportion': 60.7,
            'overallRank': 'joint 60th lightest',
            'overallConsumptionMen': 7.60,
            'overallConsumptionWomen': 1.30
        },
        'MNE': {
            'name': 'Montenegro',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.9483, 4.089, 3.6279, 0.0348],
            'overallConsumptionBothSexes': 8.70,
            'bingeDrinkingMenProportion': 13.8,
            'bingeDrinkingWomenProportion': 1.1,
            'abstainersPast12MonthsProportion': 34.8,
            'overallRank': 'joint 53rd heaviest',
            'overallConsumptionMen': 13.50,
            'overallConsumptionWomen': 4.10
        },
        'LTU': {
            'name': 'Lithuania',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [7.161, 1.2012, 5.2514, 1.7864],
            'overallConsumptionBothSexes': 15.40,
            'bingeDrinkingMenProportion': 50.4,
            'bingeDrinkingWomenProportion': 24.3,
            'abstainersPast12MonthsProportion': 34.7,
            'overallRank': 'third heaviest',
            'overallConsumptionMen': 24.40,
            'overallConsumptionWomen': 7.90
        },
        'KHM': {
            'name': 'Cambodia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.5135, 0.044, 2.9425, 0.0],
            'overallConsumptionBothSexes': 5.50,
            'bingeDrinkingMenProportion': 2.4,
            'bingeDrinkingWomenProportion': 0.2,
            'abstainersPast12MonthsProportion': 61.6,
            'overallRank': '76th lightest',
            'overallConsumptionMen': 9.60,
            'overallConsumptionWomen': 1.70
        },
        'ETH': {
            'name': 'Ethiopia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.0874, 0.0252, 0.3444, 1.7388],
            'overallConsumptionBothSexes': 4.20,
            'bingeDrinkingMenProportion': 1.2,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 84.3,
            'overallRank': '59th lightest',
            'overallConsumptionMen': 6.20,
            'overallConsumptionWomen': 2.20
        },
        'LKA': {
            'name': 'Sri Lanka',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.481, 0.0037, 3.1524, 0.0629],
            'overallConsumptionBothSexes': 3.70,
            'bingeDrinkingMenProportion': 0.8,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 81.7,
            'overallRank': '53rd lightest',
            'overallConsumptionMen': 7.30,
            'overallConsumptionWomen': 0.30
        },
        'SWZ': {
            'name': 'Swaziland',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.9152, 0.0456, 0.0399, 3.705],
            'overallConsumptionBothSexes': 5.70,
            'bingeDrinkingMenProportion': 10.8,
            'bingeDrinkingWomenProportion': 1.9,
            'abstainersPast12MonthsProportion': 56.1,
            'overallRank': 'joint 78th lightest',
            'overallConsumptionMen': 10.60,
            'overallConsumptionWomen': 1.10
        },
        'ARG': {
            'name': 'Argentina',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.7851, 4.464, 0.5115, 0.5394],
            'overallConsumptionBothSexes': 9.30,
            'bingeDrinkingMenProportion': 24.1,
            'bingeDrinkingWomenProportion': 0.8,
            'abstainersPast12MonthsProportion': 41.2,
            'overallRank': 'joint 46th heaviest',
            'overallConsumptionMen': 13.60,
            'overallConsumptionWomen': 5.20
        },
        'CMR': {
            'name': 'Cameroon',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.7296, 0.1008, 0.0168, 4.5528],
            'overallConsumptionBothSexes': 8.40,
            'bingeDrinkingMenProportion': 17.8,
            'bingeDrinkingWomenProportion': 6.8,
            'abstainersPast12MonthsProportion': 56.8,
            'overallRank': 'joint 57th heaviest',
            'overallConsumptionMen': 13.30,
            'overallConsumptionWomen': 3.50
        },
        'BFA': {
            'name': 'Burkina Faso',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.68, 0.204, 0.2108, 5.6984],
            'overallConsumptionBothSexes': 6.80,
            'bingeDrinkingMenProportion': 29.6,
            'bingeDrinkingWomenProportion': 8.7,
            'abstainersPast12MonthsProportion': 62.0,
            'overallRank': 'joint 84th heaviest',
            'overallConsumptionMen': 11.20,
            'overallConsumptionWomen': 2.80
        },
        'GHA': {
            'name': 'Ghana',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.44, 0.4656, 0.1392, 2.7504],
            'overallConsumptionBothSexes': 4.80,
            'bingeDrinkingMenProportion': 4.3,
            'bingeDrinkingWomenProportion': 0.5,
            'abstainersPast12MonthsProportion': 76.7,
            'overallRank': '68th lightest',
            'overallConsumptionMen': 7.80,
            'overallConsumptionWomen': 1.90
        },
        'SAU': {
            'name': 'Saudi Arabia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.0, 0.0038, 0.1958, 0.0004],
            'overallConsumptionBothSexes': 0.20,
            'bingeDrinkingMenProportion': 0.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 94.2,
            'overallRank': 'joint second lightest',
            'overallConsumptionMen': 0.30,
            'overallConsumptionWomen': 0.10
        },
        'SVN': {
            'name': 'Slovenia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.162, 5.4404, 0.9976, 0.0],
            'overallConsumptionBothSexes': 11.60,
            'bingeDrinkingMenProportion': 14.0,
            'bingeDrinkingWomenProportion': 1.2,
            'abstainersPast12MonthsProportion': 67.8,
            'overallRank': 'joint 24th heaviest',
            'overallConsumptionMen': 16.30,
            'overallConsumptionWomen': 7.00
        },
        'GTM': {
            'name': 'Guatemala',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.5922, 0.0608, 2.1394, 0.0076],
            'overallConsumptionBothSexes': 3.80,
            'bingeDrinkingMenProportion': 13.3,
            'bingeDrinkingWomenProportion': 2.8,
            'abstainersPast12MonthsProportion': 57.7,
            'overallRank': 'joint 54th lightest',
            'overallConsumptionMen': 7.50,
            'overallConsumptionWomen': 0.50
        },
        'BIH': {
            'name': 'Bosnia and Herzegovina',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.0661, 0.2272, 4.8067, 0.0],
            'overallConsumptionBothSexes': 7.10,
            'bingeDrinkingMenProportion': 12.4,
            'bingeDrinkingWomenProportion': 0.7,
            'abstainersPast12MonthsProportion': 42.8,
            'overallRank': 'joint 73rd heaviest',
            'overallConsumptionMen': 13.10,
            'overallConsumptionWomen': 1.40
        },
        'GIN': {
            'name': 'Guinea',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.5523, 0.1141, 0.0259, 0.0077],
            'overallConsumptionBothSexes': 0.70,
            'bingeDrinkingMenProportion': 3.3,
            'bingeDrinkingWomenProportion': 0.6,
            'abstainersPast12MonthsProportion': 91.3,
            'overallRank': 'joint 11th lightest',
            'overallConsumptionMen': 1.40,
            'overallConsumptionWomen': 0.10
        },
        'RUS': {
            'name': 'Russia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.6776, 1.7214, 7.701, 0.0],
            'overallConsumptionBothSexes': 15.10,
            'bingeDrinkingMenProportion': 29.6,
            'bingeDrinkingWomenProportion': 9.9,
            'abstainersPast12MonthsProportion': 32.2,
            'overallRank': 'fourth heaviest',
            'overallConsumptionMen': 23.90,
            'overallConsumptionWomen': 7.80
        },
        'JOR': {
            'name': 'Jordan',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.1568, 0.0147, 0.5278, 0.0007],
            'overallConsumptionBothSexes': 0.70,
            'bingeDrinkingMenProportion': 0.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 95.3,
            'overallRank': 'joint 11th lightest',
            'overallConsumptionMen': 1.20,
            'overallConsumptionWomen': 0.20
        },
        'DMA': {
            'name': 'Dominica',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.9727, 0.5041, 5.5309, 0.0852],
            'overallConsumptionBothSexes': 7.10,
            'bingeDrinkingMenProportion': 41.3,
            'bingeDrinkingWomenProportion': 9.7,
            'abstainersPast12MonthsProportion': 41.0,
            'overallRank': 'joint 73rd heaviest',
            'overallConsumptionMen': 10.20,
            'overallConsumptionWomen': 4.10
        },
        'LBR': {
            'name': 'Liberia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.5076, 0.047, 4.1407, 0.0],
            'overallConsumptionBothSexes': 4.70,
            'bingeDrinkingMenProportion': 18.9,
            'bingeDrinkingWomenProportion': 4.7,
            'abstainersPast12MonthsProportion': 70.0,
            'overallRank': '67th lightest',
            'overallConsumptionMen': 7.50,
            'overallConsumptionWomen': 2.00
        },
        'NLD': {
            'name': 'Netherlands',
            'ifNameNeedsAThePrefix': 'the ',
            'drinksData': [4.6332, 3.6036, 1.6731, 0.0],
            'overallConsumptionBothSexes': 9.90,
            'bingeDrinkingMenProportion': 11.5,
            'bingeDrinkingWomenProportion': 1.1,
            'abstainersPast12MonthsProportion': 11.8,
            'overallRank': '42nd heaviest',
            'overallConsumptionMen': 14.00,
            'overallConsumptionWomen': 6.00
        },
        'JAM': {
            'name': 'Jamaica',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.058, 0.2401, 2.5186, 0.0784],
            'overallConsumptionBothSexes': 4.90,
            'bingeDrinkingMenProportion': 11.8,
            'bingeDrinkingWomenProportion': 1.4,
            'abstainersPast12MonthsProportion': 54.2,
            'overallRank': '69th lightest',
            'overallConsumptionMen': 7.10,
            'overallConsumptionWomen': 2.80
        },
        'OMN': {
            'name': 'Oman',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.4914, 0.0297, 0.3798, 0.0],
            'overallConsumptionBothSexes': 0.90,
            'bingeDrinkingMenProportion': 0.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 94.1,
            'overallRank': 'joint 15th lightest',
            'overallConsumptionMen': 1.20,
            'overallConsumptionWomen': 0.40
        },
        'CPV': {
            'name': 'Cabo Verde',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.347, 0.5037, 1.7526, 0.2967],
            'overallConsumptionBothSexes': 6.90,
            'bingeDrinkingMenProportion': 8.8,
            'bingeDrinkingWomenProportion': 2.0,
            'abstainersPast12MonthsProportion': 61.4,
            'overallRank': 'joint 80th heaviest',
            'overallConsumptionMen': 11.20,
            'overallConsumptionWomen': 2.70
        },
        'SYC': {
            'name': 'Seychelles',
            'ifNameNeedsAThePrefix': 'the ',
            'drinksData': [3.752, 1.2432, 0.6048, 0.0],
            'overallConsumptionBothSexes': 5.60,
            'bingeDrinkingMenProportion': 37.2,
            'bingeDrinkingWomenProportion': 5.9,
            'abstainersPast12MonthsProportion': 55.8,
            'overallRank': '77th lightest',
            'overallConsumptionMen': 8.70,
            'overallConsumptionWomen': 2.40
        },
        'GAB': {
            'name': 'Gabon',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [7.4447, 1.2971, 2.1582, 0.0109],
            'overallConsumptionBothSexes': 10.90,
            'bingeDrinkingMenProportion': 8.9,
            'bingeDrinkingWomenProportion': 1.0,
            'abstainersPast12MonthsProportion': 58.9,
            'overallRank': 'joint 31st heaviest',
            'overallConsumptionMen': 17.30,
            'overallConsumptionWomen': 4.60
        },
        'NIU': {
            'name': 'Niue',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.76, 0.136, 4.104, 0.0],
            'overallConsumptionBothSexes': 8.00,
            'bingeDrinkingMenProportion': 'No data',
            'bingeDrinkingWomenProportion': 'No data',
            'abstainersPast12MonthsProportion': 56.0,
            'overallRank': 'joint 62nd heaviest',
            'overallConsumptionMen': 13.30,
            'overallConsumptionWomen': 2.60
        },
        'BHS': {
            'name': 'Bahamas',
            'ifNameNeedsAThePrefix': 'the ',
            'drinksData': [2.346, 1.0074, 3.4776, 0.069],
            'overallConsumptionBothSexes': 6.90,
            'bingeDrinkingMenProportion': 9.5,
            'bingeDrinkingWomenProportion': 0.9,
            'abstainersPast12MonthsProportion': 45.0,
            'overallRank': 'joint 80th heaviest',
            'overallConsumptionMen': 10.10,
            'overallConsumptionWomen': 3.90
        },
        'NZL': {
            'name': 'New Zealand',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.1638, 3.6951, 1.6568, 1.3625],
            'overallConsumptionBothSexes': 10.90,
            'bingeDrinkingMenProportion': 7.8,
            'bingeDrinkingWomenProportion': 0.9,
            'abstainersPast12MonthsProportion': 20.5,
            'overallRank': 'joint 31st heaviest',
            'overallConsumptionMen': 15.70,
            'overallConsumptionWomen': 6.30
        },
        'YEM': {
            'name': 'Yemen',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.3, 0.0, 0.0, 0.0],
            'overallConsumptionBothSexes': 0.30,
            'bingeDrinkingMenProportion': 0.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 95.9,
            'overallRank': 'joint fourth lightest',
            'overallConsumptionMen': 0.40,
            'overallConsumptionWomen': 0.10
        },
        'ALB': {
            'name': 'Albania',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.226, 1.386, 3.388, 0.0],
            'overallConsumptionBothSexes': 7.00,
            'bingeDrinkingMenProportion': 11.7,
            'bingeDrinkingWomenProportion': 1.0,
            'abstainersPast12MonthsProportion': 46.2,
            'overallRank': 'joint 78th heaviest',
            'overallConsumptionMen': 10.60,
            'overallConsumptionWomen': 3.40
        },
        'WSM': {
            'name': 'Samoa',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.5524, 0.5976, 0.45, 0.0],
            'overallConsumptionBothSexes': 3.60,
            'bingeDrinkingMenProportion': 27.9,
            'bingeDrinkingWomenProportion': 2.7,
            'abstainersPast12MonthsProportion': 54.7,
            'overallRank': 'joint 50th lightest',
            'overallConsumptionMen': 6.60,
            'overallConsumptionWomen': 0.60
        },
        'ARE': {
            'name': 'United Arab Emirates',
            'ifNameNeedsAThePrefix': 'the ',
            'drinksData': [0.4429, 0.1247, 3.7281, 0.0],
            'overallConsumptionBothSexes': 4.30,
            'bingeDrinkingMenProportion': 0.2,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 87.0,
            'overallRank': 'joint 60th lightest',
            'overallConsumptionMen': 5.50,
            'overallConsumptionWomen': 0.80
        },
        'CIV': {
            'name': 'Côte d\'Ivoire',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.966, 0.18, 0.024, 4.83],
            'overallConsumptionBothSexes': 6.00,
            'bingeDrinkingMenProportion': 4.9,
            'bingeDrinkingWomenProportion': 0.3,
            'abstainersPast12MonthsProportion': 76.7,
            'overallRank': '81st lightest',
            'overallConsumptionMen': 9.80,
            'overallConsumptionWomen': 1.90
        },
        'IND': {
            'name': 'India',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.2924, 0.0043, 4.0033, 0.0],
            'overallConsumptionBothSexes': 4.30,
            'bingeDrinkingMenProportion': 3.2,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 84.9,
            'overallRank': 'joint 60th lightest',
            'overallConsumptionMen': 8.00,
            'overallConsumptionWomen': 0.50
        },
        'AZE': {
            'name': 'Azerbaijan',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.6601, 0.1748, 1.4559, 0.0],
            'overallConsumptionBothSexes': 2.30,
            'bingeDrinkingMenProportion': 19.9,
            'bingeDrinkingWomenProportion': 1.2,
            'abstainersPast12MonthsProportion': 56.0,
            'overallRank': 'joint 36th lightest',
            'overallConsumptionMen': 3.60,
            'overallConsumptionWomen': 1.10
        },
        'LSO': {
            'name': 'Lesotho',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.3345, 0.013, 1.2285, 1.924],
            'overallConsumptionBothSexes': 6.50,
            'bingeDrinkingMenProportion': 6.5,
            'bingeDrinkingWomenProportion': 0.6,
            'abstainersPast12MonthsProportion': 70.0,
            'overallRank': '85th lightest',
            'overallConsumptionMen': 10.80,
            'overallConsumptionWomen': 2.50
        },
        'VCT': {
            'name': 'Saint Vincent and the Grenadines',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.2044, 0.198, 4.1646, 0.033],
            'overallConsumptionBothSexes': 6.60,
            'bingeDrinkingMenProportion': 9.6,
            'bingeDrinkingWomenProportion': 0.9,
            'abstainersPast12MonthsProportion': 44.1,
            'overallRank': 'joint 86th lightest',
            'overallConsumptionMen': 9.20,
            'overallConsumptionWomen': 3.90
        },
        'KEN': {
            'name': 'Kenya',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.4123, 0.0774, 0.9288, 0.8772],
            'overallConsumptionBothSexes': 4.30,
            'bingeDrinkingMenProportion': 2.8,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 77.3,
            'overallRank': 'joint 60th lightest',
            'overallConsumptionMen': 7.40,
            'overallConsumptionWomen': 1.30
        },
        'TJK': {
            'name': 'Tajikistan',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.2856, 0.0308, 2.4836, 0.0],
            'overallConsumptionBothSexes': 2.80,
            'bingeDrinkingMenProportion': 1.9,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 90.7,
            'overallRank': 'joint 41st lightest',
            'overallConsumptionMen': 4.30,
            'overallConsumptionWomen': 1.40
        },
        'TUR': {
            'name': 'Turkey',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.272, 0.172, 0.558, 0.0],
            'overallConsumptionBothSexes': 2.00,
            'bingeDrinkingMenProportion': 0.3,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 86.2,
            'overallRank': 'joint 31st lightest',
            'overallConsumptionMen': 4.40,
            'overallConsumptionWomen': 0.50
        },
        'CZE': {
            'name': 'Czech Republic',
            'ifNameNeedsAThePrefix': 'the ',
            'drinksData': [6.955, 2.665, 3.38, 0.0],
            'overallConsumptionBothSexes': 13.00,
            'bingeDrinkingMenProportion': 54.5,
            'bingeDrinkingWomenProportion': 18.1,
            'abstainersPast12MonthsProportion': 10.9,
            'overallRank': 'joint ninth heaviest',
            'overallConsumptionMen': 18.60,
            'overallConsumptionWomen': 7.80
        },
        'ERI': {
            'name': 'Eritrea',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.6996, 0.0, 0.0011, 0.3993],
            'overallConsumptionBothSexes': 1.10,
            'bingeDrinkingMenProportion': 1.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 56.7,
            'overallRank': 'joint 19th lightest',
            'overallConsumptionMen': 1.80,
            'overallConsumptionWomen': 0.30
        },
        'VNM': {
            'name': 'Vietnam',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [6.4218, 0.0396, 0.1386, 0.0],
            'overallConsumptionBothSexes': 6.60,
            'bingeDrinkingMenProportion': 2.4,
            'bingeDrinkingWomenProportion': 0.2,
            'abstainersPast12MonthsProportion': 61.7,
            'overallRank': 'joint 86th lightest',
            'overallConsumptionMen': 12.10,
            'overallConsumptionWomen': 0.20
        },
        'LCA': {
            'name': 'Saint Lucia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.0888, 1.3104, 5.8344, 0.156],
            'overallConsumptionBothSexes': 10.40,
            'bingeDrinkingMenProportion': 8.5,
            'bingeDrinkingWomenProportion': 0.8,
            'abstainersPast12MonthsProportion': 47.8,
            'overallRank': '35th heaviest',
            'overallConsumptionMen': 15.10,
            'overallConsumptionWomen': 5.90
        },
        'MNG': {
            'name': 'Mongolia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.9044, 0.1932, 4.8024, 0.0],
            'overallConsumptionBothSexes': 6.90,
            'bingeDrinkingMenProportion': 40.2,
            'bingeDrinkingWomenProportion': 13.6,
            'abstainersPast12MonthsProportion': 54.3,
            'overallRank': 'joint 80th heaviest',
            'overallConsumptionMen': 11.70,
            'overallConsumptionWomen': 2.20
        },
        'FRA': {
            'name': 'France',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.2936, 6.8808, 2.8182, 0.2074],
            'overallConsumptionBothSexes': 12.20,
            'bingeDrinkingMenProportion': 45.4,
            'bingeDrinkingWomenProportion': 14.4,
            'abstainersPast12MonthsProportion': 5.2,
            'overallRank': 'joint 18th heaviest',
            'overallConsumptionMen': 17.80,
            'overallConsumptionWomen': 7.10
        },
        'SYR': {
            'name': 'Syria',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.102, 0.3348, 0.762, 0.0],
            'overallConsumptionBothSexes': 1.20,
            'bingeDrinkingMenProportion': 0.1,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 92.5,
            'overallRank': '21st lightest',
            'overallConsumptionMen': 2.30,
            'overallConsumptionWomen': 0.10
        },
        'RWA': {
            'name': 'Rwanda',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.0878, 0.0, 0.0392, 8.6632],
            'overallConsumptionBothSexes': 9.80,
            'bingeDrinkingMenProportion': 30.0,
            'bingeDrinkingWomenProportion': 8.8,
            'abstainersPast12MonthsProportion': 55.3,
            'overallRank': 'joint 43rd heaviest',
            'overallConsumptionMen': 15.10,
            'overallConsumptionWomen': 5.00
        },
        'SVK': {
            'name': 'Slovakia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.913, 2.379, 6.006, 0.715],
            'overallConsumptionBothSexes': 13.00,
            'bingeDrinkingMenProportion': 41.4,
            'bingeDrinkingWomenProportion': 11.7,
            'abstainersPast12MonthsProportion': 32.4,
            'overallRank': 'joint ninth heaviest',
            'overallConsumptionMen': 20.50,
            'overallConsumptionWomen': 6.10
        },
        'PER': {
            'name': 'Peru',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.7908, 0.4941, 3.8151, 0.0],
            'overallConsumptionBothSexes': 8.10,
            'bingeDrinkingMenProportion': 22.1,
            'bingeDrinkingWomenProportion': 2.2,
            'abstainersPast12MonthsProportion': 44.6,
            'overallRank': 'joint 60th heaviest',
            'overallConsumptionMen': 12.40,
            'overallConsumptionWomen': 3.80
        },
        'VUT': {
            'name': 'Vanuatu',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.567, 0.3192, 0.5138, 0.0],
            'overallConsumptionBothSexes': 1.40,
            'bingeDrinkingMenProportion': 10.5,
            'bingeDrinkingWomenProportion': 2.4,
            'abstainersPast12MonthsProportion': 68.2,
            'overallRank': '24th lightest',
            'overallConsumptionMen': 2.50,
            'overallConsumptionWomen': 0.20
        },
        'NRU': {
            'name': 'Nauru',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.989, 0.511, 0.0, 0.0],
            'overallConsumptionBothSexes': 3.50,
            'bingeDrinkingMenProportion': 'No data',
            'bingeDrinkingWomenProportion': 'No data',
            'abstainersPast12MonthsProportion': 71.9,
            'overallRank': '49th lightest',
            'overallConsumptionMen': 5.90,
            'overallConsumptionWomen': 1.10
        },
        'NOR': {
            'name': 'Norway',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.4034, 2.6719, 1.463, 0.1617],
            'overallConsumptionBothSexes': 7.70,
            'bingeDrinkingMenProportion': 19.5,
            'bingeDrinkingWomenProportion': 5.2,
            'abstainersPast12MonthsProportion': 14.1,
            'overallRank': 'joint 65th heaviest',
            'overallConsumptionMen': 10.80,
            'overallConsumptionWomen': 4.70
        },
        'MWI': {
            'name': 'Malawi',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.2275, 0.03, 0.335, 1.905],
            'overallConsumptionBothSexes': 2.50,
            'bingeDrinkingMenProportion': 15.6,
            'bingeDrinkingWomenProportion': 1.1,
            'abstainersPast12MonthsProportion': 80.6,
            'overallRank': '40th lightest',
            'overallConsumptionMen': 4.50,
            'overallConsumptionWomen': 0.50
        },
        'COK': {
            'name': 'Cook Islands',
            'ifNameNeedsAThePrefix': 'the ',
            'drinksData': [0.0, 1.4464, 4.9536, 0.0],
            'overallConsumptionBothSexes': 6.40,
            'bingeDrinkingMenProportion': 'No data',
            'bingeDrinkingWomenProportion': 'No data',
            'abstainersPast12MonthsProportion': 54.9,
            'overallRank': 'joint 83rd lightest',
            'overallConsumptionMen': 10.50,
            'overallConsumptionWomen': 2.10
        },
        'BEN': {
            'name': 'Benin',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.1466, 0.4557, 0.1512, 0.3465],
            'overallConsumptionBothSexes': 2.10,
            'bingeDrinkingMenProportion': 35.4,
            'bingeDrinkingWomenProportion': 9.8,
            'abstainersPast12MonthsProportion': 60.6,
            'overallRank': 'joint 33rd lightest',
            'overallConsumptionMen': 3.40,
            'overallConsumptionWomen': 0.90
        },
        'CUB': {
            'name': 'Cuba',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.0176, 0.1144, 3.0628, 0.0],
            'overallConsumptionBothSexes': 5.20,
            'bingeDrinkingMenProportion': 11.3,
            'bingeDrinkingWomenProportion': 1.3,
            'abstainersPast12MonthsProportion': 37.8,
            'overallRank': '71st lightest',
            'overallConsumptionMen': 8.80,
            'overallConsumptionWomen': 1.60
        },
        'USA': {
            'name': 'United States',
            'otherNames': ['USA', 'US'],
            'ifNameNeedsAThePrefix': 'the ',
            'drinksData': [4.6, 1.5916, 3.0084, 0.0],
            'overallConsumptionBothSexes': 9.20,
            'bingeDrinkingMenProportion': 24.7,
            'bingeDrinkingWomenProportion': 7.5,
            'abstainersPast12MonthsProportion': 31.1,
            'overallRank': 'joint 48th heaviest',
            'overallConsumptionMen': 13.60,
            'overallConsumptionWomen': 4.90
        },
        'KNA': {
            'name': 'Saint Kitts and Nevis',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.608, 0.6068, 3.936, 0.0492],
            'overallConsumptionBothSexes': 8.20,
            'bingeDrinkingMenProportion': 'No data',
            'bingeDrinkingWomenProportion': 'No data',
            'abstainersPast12MonthsProportion': 57.5,
            'overallRank': '59th heaviest',
            'overallConsumptionMen': 11.80,
            'overallConsumptionWomen': 4.70
        },
        'TGO': {
            'name': 'Togo',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.1247, 0.6187, 0.0552, 0.5014],
            'overallConsumptionBothSexes': 2.30,
            'bingeDrinkingMenProportion': 36.1,
            'bingeDrinkingWomenProportion': 13.8,
            'abstainersPast12MonthsProportion': 37.2,
            'overallRank': 'joint 36th lightest',
            'overallConsumptionMen': 3.80,
            'overallConsumptionWomen': 0.90
        },
        'CHN': {
            'name': 'China',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.8626, 0.201, 4.6364, 0.0],
            'overallConsumptionBothSexes': 6.70,
            'bingeDrinkingMenProportion': 13.9,
            'bingeDrinkingWomenProportion': 0.7,
            'abstainersPast12MonthsProportion': 55.9,
            'overallRank': 'joint 86th heaviest',
            'overallConsumptionMen': 10.90,
            'overallConsumptionWomen': 2.20
        },
        'ARM': {
            'name': 'Armenia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.5141, 0.2809, 4.4997, 0.0],
            'overallConsumptionBothSexes': 5.30,
            'bingeDrinkingMenProportion': 38.3,
            'bingeDrinkingWomenProportion': 2.2,
            'abstainersPast12MonthsProportion': 36.0,
            'overallRank': '72nd lightest',
            'overallConsumptionMen': 8.00,
            'overallConsumptionWomen': 2.60
        },
        'KOR': {
            'name': 'South Korea',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.075, 0.1968, 0.369, 8.487],
            'overallConsumptionBothSexes': 12.30,
            'bingeDrinkingMenProportion': 12.0,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 55.2,
            'overallRank': 'joint 15th heaviest',
            'overallConsumptionMen': 21.00,
            'overallConsumptionWomen': 3.90
        },
        'DOM': {
            'name': 'Dominican Republic',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.7605, 0.1863, 2.9463, 0.0069],
            'overallConsumptionBothSexes': 6.90,
            'bingeDrinkingMenProportion': 24.0,
            'bingeDrinkingWomenProportion': 5.3,
            'abstainersPast12MonthsProportion': 44.8,
            'overallRank': 'joint 80th heaviest',
            'overallConsumptionMen': 9.80,
            'overallConsumptionWomen': 4.00
        },
        'BOL': {
            'name': 'Bolivia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.5312, 0.2242, 1.1387, 0.0059],
            'overallConsumptionBothSexes': 5.90,
            'bingeDrinkingMenProportion': 7.5,
            'bingeDrinkingWomenProportion': 0.4,
            'abstainersPast12MonthsProportion': 48.3,
            'overallRank': '80th lightest',
            'overallConsumptionMen': 9.10,
            'overallConsumptionWomen': 2.70
        },
        'UKR': {
            'name': 'Ukraine',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.6295, 1.251, 6.672, 0.3614],
            'overallConsumptionBothSexes': 13.90,
            'bingeDrinkingMenProportion': 35.6,
            'bingeDrinkingWomenProportion': 11.8,
            'abstainersPast12MonthsProportion': 31.7,
            'overallRank': 'sixth heaviest',
            'overallConsumptionMen': 22.00,
            'overallConsumptionWomen': 7.20
        },
        'BHR': {
            'name': 'Bahrain',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.7686, 0.1323, 1.197, 0.0021],
            'overallConsumptionBothSexes': 2.10,
            'bingeDrinkingMenProportion': 0.1,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 90.2,
            'overallRank': 'joint 33rd lightest',
            'overallConsumptionMen': 2.70,
            'overallConsumptionWomen': 1.00
        },
        'TON': {
            'name': 'Tonga',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.9264, 0.1216, 0.5488, 0.0016],
            'overallConsumptionBothSexes': 1.60,
            'bingeDrinkingMenProportion': 11.0,
            'bingeDrinkingWomenProportion': 1.5,
            'abstainersPast12MonthsProportion': 67.0,
            'overallRank': '28th lightest',
            'overallConsumptionMen': 3.00,
            'overallConsumptionWomen': 0.20
        },
        'FIN': {
            'name': 'Finland',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.658, 2.1525, 2.952, 1.5498],
            'overallConsumptionBothSexes': 12.30,
            'bingeDrinkingMenProportion': 53.6,
            'bingeDrinkingWomenProportion': 17.9,
            'abstainersPast12MonthsProportion': 32.0,
            'overallRank': 'joint 15th heaviest',
            'overallConsumptionMen': 17.50,
            'overallConsumptionWomen': 7.30
        },
        'IDN': {
            'name': 'Indonesia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.507, 0.0006, 0.0918, 0.0],
            'overallConsumptionBothSexes': 0.60,
            'bingeDrinkingMenProportion': 4.6,
            'bingeDrinkingWomenProportion': 0.2,
            'abstainersPast12MonthsProportion': 91.9,
            'overallRank': 'joint eighth lightest',
            'overallConsumptionMen': 1.10,
            'overallConsumptionWomen': 0.10
        },
        'CAF': {
            'name': 'Central African Republic',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.6156, 0.0228, 0.0798, 3.0818],
            'overallConsumptionBothSexes': 3.80,
            'bingeDrinkingMenProportion': 3.2,
            'bingeDrinkingWomenProportion': 0.2,
            'abstainersPast12MonthsProportion': 78.6,
            'overallRank': 'joint 54th lightest',
            'overallConsumptionMen': 5.70,
            'overallConsumptionWomen': 1.90
        },
        'MUS': {
            'name': 'Mauritius',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.3832, 0.4428, 0.7668, 0.0072],
            'overallConsumptionBothSexes': 3.60,
            'bingeDrinkingMenProportion': 20.4,
            'bingeDrinkingWomenProportion': 3.7,
            'abstainersPast12MonthsProportion': 68.0,
            'overallRank': 'joint 50th lightest',
            'overallConsumptionMen': 5.90,
            'overallConsumptionWomen': 1.40
        },
        'SWE': {
            'name': 'Sweden',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.404, 4.2872, 1.3892, 0.1288],
            'overallConsumptionBothSexes': 9.20,
            'bingeDrinkingMenProportion': 36.3,
            'bingeDrinkingWomenProportion': 11.8,
            'abstainersPast12MonthsProportion': 31.2,
            'overallRank': 'joint 48th heaviest',
            'overallConsumptionMen': 12.90,
            'overallConsumptionWomen': 5.50
        },
        'BLR': {
            'name': 'Belarus',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.0275, 0.91, 8.155, 5.4075],
            'overallConsumptionBothSexes': 17.50,
            'bingeDrinkingMenProportion': 47.6,
            'bingeDrinkingWomenProportion': 7.2,
            'abstainersPast12MonthsProportion': 20.8,
            'overallRank': ' heaviest',
            'overallConsumptionMen': 27.50,
            'overallConsumptionWomen': 9.10
        },
        'MLI': {
            'name': 'Mali',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.1463, 0.0165, 0.0231, 0.9141],
            'overallConsumptionBothSexes': 1.10,
            'bingeDrinkingMenProportion': 0.2,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 96.2,
            'overallRank': 'joint 19th lightest',
            'overallConsumptionMen': 2.20,
            'overallConsumptionWomen': 0.00
        },
        'BGR': {
            'name': 'Bulgaria',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.4802, 1.881, 5.0274, 0.0114],
            'overallConsumptionBothSexes': 11.40,
            'bingeDrinkingMenProportion': 28.0,
            'bingeDrinkingWomenProportion': 9.6,
            'abstainersPast12MonthsProportion': 32.6,
            'overallRank': 'joint 26th heaviest',
            'overallConsumptionMen': 17.90,
            'overallConsumptionWomen': 5.30
        },
        'ROU': {
            'name': 'Romania',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [7.2, 4.1616, 3.0384, 0.0],
            'overallConsumptionBothSexes': 14.40,
            'bingeDrinkingMenProportion': 14.5,
            'bingeDrinkingWomenProportion': 1.2,
            'abstainersPast12MonthsProportion': 32.4,
            'overallRank': 'fifth heaviest',
            'overallConsumptionMen': 22.60,
            'overallConsumptionWomen': 6.80
        },
        'AGO': {
            'name': 'Angola',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.8225, 1.0275, 1.305, 0.3525],
            'overallConsumptionBothSexes': 7.50,
            'bingeDrinkingMenProportion': 7.5,
            'bingeDrinkingWomenProportion': 0.6,
            'abstainersPast12MonthsProportion': 64.4,
            'overallRank': '69th heaviest',
            'overallConsumptionMen': 12.00,
            'overallConsumptionWomen': 3.00
        },
        'PRT': {
            'name': 'Portugal',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.9732, 7.1595, 1.4061, 0.3612],
            'overallConsumptionBothSexes': 12.90,
            'bingeDrinkingMenProportion': 30.0,
            'bingeDrinkingWomenProportion': 9.4,
            'abstainersPast12MonthsProportion': 43.0,
            'overallRank': '11th heaviest',
            'overallConsumptionMen': 18.70,
            'overallConsumptionWomen': 7.60
        },
        'ZAF': {
            'name': 'South Africa',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.291, 1.958, 1.837, 1.914],
            'overallConsumptionBothSexes': 11.00,
            'bingeDrinkingMenProportion': 17.5,
            'bingeDrinkingWomenProportion': 2.9,
            'abstainersPast12MonthsProportion': 'No data',
            'overallRank': 'joint 29th heaviest',
            'overallConsumptionMen': 18.40,
            'overallConsumptionWomen': 4.20
        },
        'FJI': {
            'name': 'Fiji',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.031, 0.027, 0.933, 0.006],
            'overallConsumptionBothSexes': 3.00,
            'bingeDrinkingMenProportion': 16.7,
            'bingeDrinkingWomenProportion': 2.9,
            'abstainersPast12MonthsProportion': 58.6,
            'overallRank': 'joint 43rd lightest',
            'overallConsumptionMen': 5.50,
            'overallConsumptionWomen': 0.50
        },
        'BRN': {
            'name': 'Brunei',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.8082, 0.0207, 0.0648, 0.0063],
            'overallConsumptionBothSexes': 0.90,
            'bingeDrinkingMenProportion': 0.9,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 79.6,
            'overallRank': 'joint 15th lightest',
            'overallConsumptionMen': 1.60,
            'overallConsumptionWomen': 0.10
        },
        'QAT': {
            'name': 'Qatar',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.018, 0.2085, 1.269, 0.0045],
            'overallConsumptionBothSexes': 1.50,
            'bingeDrinkingMenProportion': 0.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 93.3,
            'overallRank': 'joint 25th lightest',
            'overallConsumptionMen': 1.80,
            'overallConsumptionWomen': 0.40
        },
        'MYS': {
            'name': 'Malaysia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.9906, 0.026, 0.2834, 0.0013],
            'overallConsumptionBothSexes': 1.30,
            'bingeDrinkingMenProportion': 0.6,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 87.6,
            'overallRank': 'joint 22nd lightest',
            'overallConsumptionMen': 2.50,
            'overallConsumptionWomen': 0.20
        },
        'SEN': {
            'name': 'Senegal',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.3306, 0.2478, 0.0216, 0.0],
            'overallConsumptionBothSexes': 0.60,
            'bingeDrinkingMenProportion': 0.5,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 94.5,
            'overallRank': 'joint eighth lightest',
            'overallConsumptionMen': 1.10,
            'overallConsumptionWomen': 0.10
        },
        'MOZ': {
            'name': 'Mozambique',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.449, 0.1679, 0.5842, 0.0989],
            'overallConsumptionBothSexes': 2.30,
            'bingeDrinkingMenProportion': 2.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 82.1,
            'overallRank': 'joint 36th lightest',
            'overallConsumptionMen': 3.50,
            'overallConsumptionWomen': 1.10
        },
        'UGA': {
            'name': 'Uganda',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.9212, 0.0098, 0.1862, 8.6828],
            'overallConsumptionBothSexes': 9.80,
            'bingeDrinkingMenProportion': 7.6,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 58.7,
            'overallRank': 'joint 43rd heaviest',
            'overallConsumptionMen': 14.40,
            'overallConsumptionWomen': 5.20
        },
        'HUN': {
            'name': 'Hungary',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.8279, 3.9102, 4.5619, 0.0],
            'overallConsumptionBothSexes': 13.30,
            'bingeDrinkingMenProportion': 44.4,
            'bingeDrinkingWomenProportion': 7.6,
            'abstainersPast12MonthsProportion': 18.6,
            'overallRank': 'eighth heaviest',
            'overallConsumptionMen': 20.40,
            'overallConsumptionWomen': 7.10
        },
        'NER': {
            'name': 'Niger',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.138, 0.0396, 0.1221, 0.0],
            'overallConsumptionBothSexes': 0.30,
            'bingeDrinkingMenProportion': 0.3,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 94.7,
            'overallRank': 'joint fourth lightest',
            'overallConsumptionMen': 0.50,
            'overallConsumptionWomen': 0.10
        },
        'BRA': {
            'name': 'Brazil',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.1852, 0.348, 3.1581, 0.0087],
            'overallConsumptionBothSexes': 8.70,
            'bingeDrinkingMenProportion': 20.0,
            'bingeDrinkingWomenProportion': 4.5,
            'abstainersPast12MonthsProportion': 42.3,
            'overallRank': 'joint 53rd heaviest',
            'overallConsumptionMen': 13.60,
            'overallConsumptionWomen': 4.20
        },
        'KWT': {
            'name': 'Kuwait',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.0581, 0.0108, 0.0307, 0.0004],
            'overallConsumptionBothSexes': 0.10,
            'bingeDrinkingMenProportion': 0.5,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 90.3,
            'overallRank': ' lightest',
            'overallConsumptionMen': 0.20,
            'overallConsumptionWomen': 0.00
        },
        'PAN': {
            'name': 'Panama',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.536, 0.368, 2.08, 0.016],
            'overallConsumptionBothSexes': 8.00,
            'bingeDrinkingMenProportion': 11.2,
            'bingeDrinkingWomenProportion': 0.2,
            'abstainersPast12MonthsProportion': 40.2,
            'overallRank': 'joint 62nd heaviest',
            'overallConsumptionMen': 11.20,
            'overallConsumptionWomen': 4.70
        },
        'GUY': {
            'name': 'Guyana',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.863, 0.0243, 6.2046, 0.0081],
            'overallConsumptionBothSexes': 8.10,
            'bingeDrinkingMenProportion': 9.9,
            'bingeDrinkingWomenProportion': 1.1,
            'abstainersPast12MonthsProportion': 40.5,
            'overallRank': 'joint 60th heaviest',
            'overallConsumptionMen': 11.70,
            'overallConsumptionWomen': 4.70
        },
        'MDA': {
            'name': 'Moldova',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.1072, 0.8568, 10.836, 0.0],
            'overallConsumptionBothSexes': 16.80,
            'bingeDrinkingMenProportion': 49.1,
            'bingeDrinkingWomenProportion': 16.5,
            'abstainersPast12MonthsProportion': 33.7,
            'overallRank': 'second heaviest',
            'overallConsumptionMen': 25.90,
            'overallConsumptionWomen': 8.90
        },
        'CRI': {
            'name': 'Costa Rica',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.2022, 0.2538, 1.917, 0.027],
            'overallConsumptionBothSexes': 5.40,
            'bingeDrinkingMenProportion': 12.2,
            'bingeDrinkingWomenProportion': 1.5,
            'abstainersPast12MonthsProportion': 48.6,
            'overallRank': 'joint 73rd lightest',
            'overallConsumptionMen': 7.50,
            'overallConsumptionWomen': 3.20
        },
        'LUX': {
            'name': 'Luxembourg',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.3078, 5.0932, 2.499, 0.0],
            'overallConsumptionBothSexes': 11.90,
            'bingeDrinkingMenProportion': 38.3,
            'bingeDrinkingWomenProportion': 9.0,
            'abstainersPast12MonthsProportion': 6.1,
            'overallRank': 'joint 21st heaviest',
            'overallConsumptionMen': 16.80,
            'overallConsumptionWomen': 7.20
        },
        'AND': {
            'name': 'Andorra',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.7748, 6.2514, 2.7738, 0.0],
            'overallConsumptionBothSexes': 13.80,
            'bingeDrinkingMenProportion': 7.5,
            'bingeDrinkingWomenProportion': 0.7,
            'abstainersPast12MonthsProportion': 31.7,
            'overallRank': 'seventh heaviest',
            'overallConsumptionMen': 19.50,
            'overallConsumptionWomen': 8.20
        },
        'IRL': {
            'name': 'Ireland',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.7239, 3.1059, 2.2253, 0.9163],
            'overallConsumptionBothSexes': 11.90,
            'bingeDrinkingMenProportion': 53.8,
            'bingeDrinkingWomenProportion': 19.3,
            'abstainersPast12MonthsProportion': 19.1,
            'overallRank': 'joint 21st heaviest',
            'overallConsumptionMen': 16.80,
            'overallConsumptionWomen': 7.10
        },
        'ITA': {
            'name': 'Italy',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.541, 4.3952, 0.7705, 0.0],
            'overallConsumptionBothSexes': 6.70,
            'bingeDrinkingMenProportion': 8.8,
            'bingeDrinkingWomenProportion': 0.6,
            'abstainersPast12MonthsProportion': 32.4,
            'overallRank': 'joint 86th heaviest',
            'overallConsumptionMen': 9.70,
            'overallConsumptionWomen': 3.90
        },
        'NGA': {
            'name': 'Nigeria',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.808, 0.0404, 0.0909, 9.1607],
            'overallConsumptionBothSexes': 10.10,
            'bingeDrinkingMenProportion': 12.0,
            'bingeDrinkingWomenProportion': 1.9,
            'abstainersPast12MonthsProportion': 56.4,
            'overallRank': '41st heaviest',
            'overallConsumptionMen': 14.90,
            'overallConsumptionWomen': 5.10
        },
        'ECU': {
            'name': 'Ecuador',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.8456, 0.0864, 2.268, 0.0],
            'overallConsumptionBothSexes': 7.20,
            'bingeDrinkingMenProportion': 7.0,
            'bingeDrinkingWomenProportion': 0.3,
            'abstainersPast12MonthsProportion': 52.7,
            'overallRank': 'joint 70th heaviest',
            'overallConsumptionMen': 11.10,
            'overallConsumptionWomen': 3.40
        },
        'AUS': {
            'name': 'Australia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.368, 4.4774, 1.525, 0.8296],
            'overallConsumptionBothSexes': 12.20,
            'bingeDrinkingMenProportion': 17.5,
            'bingeDrinkingWomenProportion': 2.7,
            'abstainersPast12MonthsProportion': 16.0,
            'overallRank': 'joint 18th heaviest',
            'overallConsumptionMen': 17.30,
            'overallConsumptionWomen': 7.20
        },
        'DZA': {
            'name': 'Algeria',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.626, 0.355, 0.0, 0.02],
            'overallConsumptionBothSexes': 1.00,
            'bingeDrinkingMenProportion': 0.7,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 90.7,
            'overallRank': '18th lightest',
            'overallConsumptionMen': 1.60,
            'overallConsumptionWomen': 0.40
        },
        'SLV': {
            'name': 'El Salvador',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.3344, 0.0544, 1.8112, 0.0],
            'overallConsumptionBothSexes': 3.20,
            'bingeDrinkingMenProportion': 16.3,
            'bingeDrinkingWomenProportion': 2.9,
            'abstainersPast12MonthsProportion': 56.0,
            'overallRank': '46th lightest',
            'overallConsumptionMen': 5.00,
            'overallConsumptionWomen': 1.70
        },
        'TUV': {
            'name': 'Tuvalu',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.15, 0.2325, 1.1175, 0.0],
            'overallConsumptionBothSexes': 1.50,
            'bingeDrinkingMenProportion': 'No data',
            'bingeDrinkingWomenProportion': 'No data',
            'abstainersPast12MonthsProportion': 75.6,
            'overallRank': 'joint 25th lightest',
            'overallConsumptionMen': 2.50,
            'overallConsumptionWomen': 0.50
        },
        'SLB': {
            'name': 'Solomon Islands',
            'ifNameNeedsAThePrefix': 'the ',
            'drinksData': [1.3787, 0.0357, 0.2839, 0.0],
            'overallConsumptionBothSexes': 1.70,
            'bingeDrinkingMenProportion': 24.9,
            'bingeDrinkingWomenProportion': 3.5,
            'abstainersPast12MonthsProportion': 94.6,
            'overallRank': '29th lightest',
            'overallConsumptionMen': 3.10,
            'overallConsumptionWomen': 0.30
        },
        'CHL': {
            'name': 'Chile',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.8704, 3.9072, 2.8224, 0.0],
            'overallConsumptionBothSexes': 9.60,
            'bingeDrinkingMenProportion': 9.7,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 34.1,
            'overallRank': '45th heaviest',
            'overallConsumptionMen': 13.90,
            'overallConsumptionWomen': 5.50
        },
        'BEL': {
            'name': 'Belgium',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.412, 3.993, 1.584, 0.011],
            'overallConsumptionBothSexes': 11.00,
            'bingeDrinkingMenProportion': 49.6,
            'bingeDrinkingWomenProportion': 17.6,
            'abstainersPast12MonthsProportion': 17.7,
            'overallRank': 'joint 29th heaviest',
            'overallConsumptionMen': 15.00,
            'overallConsumptionWomen': 6.30
        },
        'THA': {
            'name': 'Thailand',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.917, 0.0284, 5.1546, 0.0],
            'overallConsumptionBothSexes': 7.10,
            'bingeDrinkingMenProportion': 2.3,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 70.3,
            'overallRank': 'joint 73rd heaviest',
            'overallConsumptionMen': 13.80,
            'overallConsumptionWomen': 0.80
        },
        'HTI': {
            'name': 'Haiti',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.0128, 0.0128, 6.3744, 0.0],
            'overallConsumptionBothSexes': 6.40,
            'bingeDrinkingMenProportion': 9.4,
            'bingeDrinkingWomenProportion': 0.9,
            'abstainersPast12MonthsProportion': 44.6,
            'overallRank': 'joint 83rd lightest',
            'overallConsumptionMen': 10.10,
            'overallConsumptionWomen': 2.90
        },
        'BLZ': {
            'name': 'Belize',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.746, 0.17, 2.5755, 0.0085],
            'overallConsumptionBothSexes': 8.50,
            'bingeDrinkingMenProportion': 4.3,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 71.4,
            'overallRank': '56th heaviest',
            'overallConsumptionMen': 14.50,
            'overallConsumptionWomen': 2.50
        },
        'SLE': {
            'name': 'Sierra Leone',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.5568, 0.0435, 0.0609, 8.0301],
            'overallConsumptionBothSexes': 8.70,
            'bingeDrinkingMenProportion': 13.1,
            'bingeDrinkingWomenProportion': 4.6,
            'abstainersPast12MonthsProportion': 55.3,
            'overallRank': 'joint 53rd heaviest',
            'overallConsumptionMen': 14.00,
            'overallConsumptionWomen': 3.60
        },
        'GEO': {
            'name': 'Georgia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.309, 3.8346, 2.5564, 0.0077],
            'overallConsumptionBothSexes': 7.70,
            'bingeDrinkingMenProportion': 19.1,
            'bingeDrinkingWomenProportion': 0.6,
            'abstainersPast12MonthsProportion': 63.9,
            'overallRank': 'joint 65th heaviest',
            'overallConsumptionMen': 12.60,
            'overallConsumptionWomen': 3.40
        },
        'DNK': {
            'name': 'Denmark',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.2978, 5.4948, 1.6074, 0.0],
            'overallConsumptionBothSexes': 11.40,
            'bingeDrinkingMenProportion': 41.9,
            'bingeDrinkingWomenProportion': 15.8,
            'abstainersPast12MonthsProportion': 11.4,
            'overallRank': 'joint 26th heaviest',
            'overallConsumptionMen': 16.10,
            'overallConsumptionWomen': 6.90
        },
        'POL': {
            'name': 'Poland',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [6.8875, 1.1625, 4.4375, 0.0],
            'overallConsumptionBothSexes': 12.50,
            'bingeDrinkingMenProportion': 10.3,
            'bingeDrinkingWomenProportion': 0.6,
            'abstainersPast12MonthsProportion': 48.3,
            'overallRank': 'joint 13th heaviest',
            'overallConsumptionMen': 19.80,
            'overallConsumptionWomen': 5.80
        },
        'MAR': {
            'name': 'Morocco',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.3915, 0.3285, 0.1791, 0.0],
            'overallConsumptionBothSexes': 0.90,
            'bingeDrinkingMenProportion': 0.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 94.6,
            'overallRank': 'joint 15th lightest',
            'overallConsumptionMen': 1.90,
            'overallConsumptionWomen': 0.10
        },
        'NAM': {
            'name': 'Namibia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [10.4436, 0.0324, 0.0972, 0.2268],
            'overallConsumptionBothSexes': 10.80,
            'bingeDrinkingMenProportion': 20.9,
            'bingeDrinkingWomenProportion': 5.4,
            'abstainersPast12MonthsProportion': 61.0,
            'overallRank': '33rd heaviest',
            'overallConsumptionMen': 16.70,
            'overallConsumptionWomen': 5.40
        },
        'GNB': {
            'name': 'Guinea-Bissau',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.784, 0.596, 0.896, 1.72],
            'overallConsumptionBothSexes': 4.00,
            'bingeDrinkingMenProportion': 7.5,
            'bingeDrinkingWomenProportion': 0.7,
            'abstainersPast12MonthsProportion': 70.0,
            'overallRank': 'joint 56th lightest',
            'overallConsumptionMen': 6.40,
            'overallConsumptionWomen': 1.70
        },
        'TZA': {
            'name': 'Tanzania',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.847, 0.0154, 0.1386, 6.699],
            'overallConsumptionBothSexes': 7.70,
            'bingeDrinkingMenProportion': 22.3,
            'bingeDrinkingWomenProportion': 6.1,
            'abstainersPast12MonthsProportion': 58.1,
            'overallRank': 'joint 65th heaviest',
            'overallConsumptionMen': 11.40,
            'overallConsumptionWomen': 4.00
        },
        'CHE': {
            'name': 'Switzerland',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.4026, 5.2858, 1.8832, 0.1284],
            'overallConsumptionBothSexes': 10.70,
            'bingeDrinkingMenProportion': 28.4,
            'bingeDrinkingWomenProportion': 9.7,
            'abstainersPast12MonthsProportion': 11.5,
            'overallRank': '34th heaviest',
            'overallConsumptionMen': 15.20,
            'overallConsumptionWomen': 6.40
        },
        'GRD': {
            'name': 'Grenada',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.6625, 0.5375, 8.275, 0.025],
            'overallConsumptionBothSexes': 12.50,
            'bingeDrinkingMenProportion': 7.6,
            'bingeDrinkingWomenProportion': 0.7,
            'abstainersPast12MonthsProportion': 51.6,
            'overallRank': 'joint 13th heaviest',
            'overallConsumptionMen': 17.90,
            'overallConsumptionWomen': 7.30
        },
        'VEN': {
            'name': 'Venezuela',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [6.7284, 0.0712, 2.0826, 0.0178],
            'overallConsumptionBothSexes': 8.90,
            'bingeDrinkingMenProportion': 37.8,
            'bingeDrinkingWomenProportion': 6.5,
            'abstainersPast12MonthsProportion': 40.9,
            'overallRank': '51st heaviest',
            'overallConsumptionMen': 12.70,
            'overallConsumptionWomen': 5.20
        },
        'IRQ': {
            'name': 'Iraq',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.3805, 0.005, 0.1145, 0.0],
            'overallConsumptionBothSexes': 0.50,
            'bingeDrinkingMenProportion': 0.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 94.6,
            'overallRank': 'seventh lightest',
            'overallConsumptionMen': 0.90,
            'overallConsumptionWomen': 0.10
        },
        'TCD': {
            'name': 'Chad',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.9172, 0.1496, 0.1672, 1.166],
            'overallConsumptionBothSexes': 4.40,
            'bingeDrinkingMenProportion': 1.6,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 86.9,
            'overallRank': '65th lightest',
            'overallConsumptionMen': 7.10,
            'overallConsumptionWomen': 1.80
        },
        'EST': {
            'name': 'Estonia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.2436, 1.1433, 3.7904, 1.1227],
            'overallConsumptionBothSexes': 10.30,
            'bingeDrinkingMenProportion': 41.4,
            'bingeDrinkingWomenProportion': 9.1,
            'abstainersPast12MonthsProportion': 34.8,
            'overallRank': 'joint 36th heaviest',
            'overallConsumptionMen': 16.20,
            'overallConsumptionWomen': 5.30
        },
        'URY': {
            'name': 'Uruguay',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.3256, 4.5524, 0.722, 0.0],
            'overallConsumptionBothSexes': 7.60,
            'bingeDrinkingMenProportion': 14.8,
            'bingeDrinkingWomenProportion': 4.6,
            'abstainersPast12MonthsProportion': 41.3,
            'overallRank': '68th heaviest',
            'overallConsumptionMen': 11.30,
            'overallConsumptionWomen': 4.20
        },
        'MEX': {
            'name': 'Mexico',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.4504, 0.108, 1.5984, 0.036],
            'overallConsumptionBothSexes': 7.20,
            'bingeDrinkingMenProportion': 19.6,
            'bingeDrinkingWomenProportion': 3.3,
            'abstainersPast12MonthsProportion': 43.1,
            'overallRank': 'joint 70th heaviest',
            'overallConsumptionMen': 12.40,
            'overallConsumptionWomen': 2.60
        },
        'LBN': {
            'name': 'Lebanon',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.4368, 0.6984, 1.2576, 0.0072],
            'overallConsumptionBothSexes': 2.40,
            'bingeDrinkingMenProportion': 0.1,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 89.9,
            'overallRank': '39th lightest',
            'overallConsumptionMen': 3.90,
            'overallConsumptionWomen': 0.80
        },
        'UZB': {
            'name': 'Uzbekistan',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.8418, 0.2898, 3.4684, 0.0],
            'overallConsumptionBothSexes': 4.60,
            'bingeDrinkingMenProportion': 20.4,
            'bingeDrinkingWomenProportion': 0.4,
            'abstainersPast12MonthsProportion': 62.8,
            'overallRank': '66th lightest',
            'overallConsumptionMen': 7.90,
            'overallConsumptionWomen': 1.30
        },
        'EGY': {
            'name': 'Egypt',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.2152, 0.0216, 0.1612, 0.002],
            'overallConsumptionBothSexes': 0.40,
            'bingeDrinkingMenProportion': 0.1,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 93.5,
            'overallRank': 'sixth lightest',
            'overallConsumptionMen': 0.70,
            'overallConsumptionWomen': 0.00
        },
        'DJI': {
            'name': 'Djibouti',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.3016, 0.0689, 0.9295, 0.0],
            'overallConsumptionBothSexes': 1.30,
            'bingeDrinkingMenProportion': 0.2,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 94.2,
            'overallRank': 'joint 22nd lightest',
            'overallConsumptionMen': 2.40,
            'overallConsumptionWomen': 0.30
        },
        'ATG': {
            'name': 'Antigua and Barbuda',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.9656, 0.8856, 2.538, 0.0162],
            'overallConsumptionBothSexes': 5.40,
            'bingeDrinkingMenProportion': 11.3,
            'bingeDrinkingWomenProportion': 1.5,
            'abstainersPast12MonthsProportion': 33.4,
            'overallRank': 'joint 73rd lightest',
            'overallConsumptionMen': 7.70,
            'overallConsumptionWomen': 3.10
        },
        'ESP': {
            'name': 'Spain',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.5664, 2.2512, 3.1584, 0.2016],
            'overallConsumptionBothSexes': 11.20,
            'bingeDrinkingMenProportion': 20.3,
            'bingeDrinkingWomenProportion': 5.9,
            'abstainersPast12MonthsProportion': 31.7,
            'overallRank': '28th heaviest',
            'overallConsumptionMen': 15.90,
            'overallConsumptionWomen': 6.70
        },
        'COL': {
            'name': 'Colombia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.0982, 0.0682, 2.015, 0.0186],
            'overallConsumptionBothSexes': 6.20,
            'bingeDrinkingMenProportion': 8.2,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 51.7,
            'overallRank': '82nd lightest',
            'overallConsumptionMen': 9.10,
            'overallConsumptionWomen': 3.50
        },
        'BDI': {
            'name': 'Burundi',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.2785, 0.0, 0.0093, 7.0122],
            'overallConsumptionBothSexes': 9.30,
            'bingeDrinkingMenProportion': 6.7,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 57.9,
            'overallRank': 'joint 46th heaviest',
            'overallConsumptionMen': 13.90,
            'overallConsumptionWomen': 4.80
        },
        'CYP': {
            'name': 'Cyprus',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.7628, 2.2724, 3.1004, 0.0644],
            'overallConsumptionBothSexes': 9.20,
            'bingeDrinkingMenProportion': 42.4,
            'bingeDrinkingWomenProportion': 7.1,
            'abstainersPast12MonthsProportion': 15.0,
            'overallRank': 'joint 48th heaviest',
            'overallConsumptionMen': 12.50,
            'overallConsumptionWomen': 5.70
        },
        'BRB': {
            'name': 'Barbados',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.6996, 0.6936, 3.3524, 0.0544],
            'overallConsumptionBothSexes': 6.80,
            'bingeDrinkingMenProportion': 24.3,
            'bingeDrinkingWomenProportion': 3.8,
            'abstainersPast12MonthsProportion': 31.4,
            'overallRank': 'joint 84th heaviest',
            'overallConsumptionMen': 9.80,
            'overallConsumptionWomen': 4.00
        },
        'MDG': {
            'name': 'Madagascar',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.008, 0.171, 0.621, 0.0],
            'overallConsumptionBothSexes': 1.80,
            'bingeDrinkingMenProportion': 15.5,
            'bingeDrinkingWomenProportion': 2.4,
            'abstainersPast12MonthsProportion': 85.9,
            'overallRank': '30th lightest',
            'overallConsumptionMen': 2.90,
            'overallConsumptionWomen': 0.70
        },
        'PLW': {
            'name': 'Palau',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [6.1383, 0.4661, 1.2956, 0.0],
            'overallConsumptionBothSexes': 7.90,
            'bingeDrinkingMenProportion': 'No data',
            'bingeDrinkingWomenProportion': 'No data',
            'abstainersPast12MonthsProportion': 45.0,
            'overallRank': '64th heaviest',
            'overallConsumptionMen': 13.20,
            'overallConsumptionWomen': 2.60
        },
        'BTN': {
            'name': 'Bhutan',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.7, 0.0, 0.0, 0.0],
            'overallConsumptionBothSexes': 0.70,
            'bingeDrinkingMenProportion': 1.2,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 89.7,
            'overallRank': 'joint 11th lightest',
            'overallConsumptionMen': 1.20,
            'overallConsumptionWomen': 0.10
        },
        'SRB': {
            'name': 'Serbia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [6.489, 3.0114, 3.0996, 0.0],
            'overallConsumptionBothSexes': 12.60,
            'bingeDrinkingMenProportion': 14.0,
            'bingeDrinkingWomenProportion': 1.1,
            'abstainersPast12MonthsProportion': 34.0,
            'overallRank': '12th heaviest',
            'overallConsumptionMen': 19.70,
            'overallConsumptionWomen': 5.90
        },
        'NPL': {
            'name': 'Nepal',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.0494, 0.0198, 1.1308, 0.0],
            'overallConsumptionBothSexes': 2.20,
            'bingeDrinkingMenProportion': 0.8,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 92.4,
            'overallRank': '35th lightest',
            'overallConsumptionMen': 4.40,
            'overallConsumptionWomen': 0.20
        },
        'KIR': {
            'name': 'Kiribati',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.107, 0.066, 1.827, 0.0],
            'overallConsumptionBothSexes': 3.00,
            'bingeDrinkingMenProportion': 4.4,
            'bingeDrinkingWomenProportion': 0.3,
            'abstainersPast12MonthsProportion': 69.0,
            'overallRank': 'joint 43rd lightest',
            'overallConsumptionMen': 5.50,
            'overallConsumptionWomen': 0.40
        },
        'MLT': {
            'name': 'Malta',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.758, 2.289, 1.904, 0.049],
            'overallConsumptionBothSexes': 7.00,
            'bingeDrinkingMenProportion': 40.1,
            'bingeDrinkingWomenProportion': 12.3,
            'abstainersPast12MonthsProportion': 39.4,
            'overallRank': 'joint 78th heaviest',
            'overallConsumptionMen': 9.70,
            'overallConsumptionWomen': 4.20
        },
        'COD': {
            'name': 'DR Congo',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.864, 0.0252, 0.072, 2.6388],
            'overallConsumptionBothSexes': 3.60,
            'bingeDrinkingMenProportion': 5.7,
            'bingeDrinkingWomenProportion': 0.2,
            'abstainersPast12MonthsProportion': 72.1,
            'overallRank': 'joint 50th lightest',
            'overallConsumptionMen': 5.80,
            'overallConsumptionWomen': 1.50
        },
        'SUR': {
            'name': 'Suriname',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.64, 0.1518, 3.7752, 0.033],
            'overallConsumptionBothSexes': 6.60,
            'bingeDrinkingMenProportion': 8.2,
            'bingeDrinkingWomenProportion': 0.8,
            'abstainersPast12MonthsProportion': 48.1,
            'overallRank': 'joint 86th lightest',
            'overallConsumptionMen': 9.40,
            'overallConsumptionWomen': 3.90
        },
        'FSM': {
            'name': 'Micronesia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.551, 0.4653, 1.2837, 0.0],
            'overallConsumptionBothSexes': 3.30,
            'bingeDrinkingMenProportion': 19.5,
            'bingeDrinkingWomenProportion': 3.1,
            'abstainersPast12MonthsProportion': 59.3,
            'overallRank': '47th lightest',
            'overallConsumptionMen': 6.00,
            'overallConsumptionWomen': 0.50
        },
        'MKD': {
            'name': 'Macedonia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.1758, 2.6733, 0.8442, 0.0],
            'overallConsumptionBothSexes': 6.70,
            'bingeDrinkingMenProportion': 12.3,
            'bingeDrinkingWomenProportion': 0.7,
            'abstainersPast12MonthsProportion': 42.9,
            'overallRank': 'joint 86th heaviest',
            'overallConsumptionMen': 10.20,
            'overallConsumptionWomen': 3.20
        },
        'ISR': {
            'name': 'Israel',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.232, 0.1736, 1.386, 0.0084],
            'overallConsumptionBothSexes': 2.80,
            'bingeDrinkingMenProportion': 12.6,
            'bingeDrinkingWomenProportion': 2.4,
            'abstainersPast12MonthsProportion': 48.1,
            'overallRank': 'joint 41st lightest',
            'overallConsumptionMen': 4.00,
            'overallConsumptionWomen': 1.70
        },
        'ISL': {
            'name': 'Iceland',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.3878, 1.5052, 1.1715, 0.0355],
            'overallConsumptionBothSexes': 7.10,
            'bingeDrinkingMenProportion': 34.3,
            'bingeDrinkingWomenProportion': 11.0,
            'abstainersPast12MonthsProportion': 32.1,
            'overallRank': 'joint 73rd heaviest',
            'overallConsumptionMen': 9.80,
            'overallConsumptionWomen': 4.30
        },
        'ZMB': {
            'name': 'Zambia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.908, 0.116, 0.544, 2.428],
            'overallConsumptionBothSexes': 4.00,
            'bingeDrinkingMenProportion': 5.0,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 69.4,
            'overallRank': 'joint 56th lightest',
            'overallConsumptionMen': 6.50,
            'overallConsumptionWomen': 1.60
        },
        'AUT': {
            'name': 'Austria',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.1912, 3.6565, 1.442, 0.0],
            'overallConsumptionBothSexes': 10.30,
            'bingeDrinkingMenProportion': 53.5,
            'bingeDrinkingWomenProportion': 23.6,
            'abstainersPast12MonthsProportion': 22.6,
            'overallRank': 'joint 36th heaviest',
            'overallConsumptionMen': 15.40,
            'overallConsumptionWomen': 6.30
        },
        'PNG': {
            'name': 'Papua New Guinea',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.539, 0.027, 1.398, 0.0],
            'overallConsumptionBothSexes': 3.00,
            'bingeDrinkingMenProportion': 15.9,
            'bingeDrinkingWomenProportion': 1.2,
            'abstainersPast12MonthsProportion': 65.4,
            'overallRank': 'joint 43rd lightest',
            'overallConsumptionMen': 5.10,
            'overallConsumptionWomen': 1.00
        },
        'ZWE': {
            'name': 'Zimbabwe',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.3509, 0.0969, 0.3876, 3.8589],
            'overallConsumptionBothSexes': 5.70,
            'bingeDrinkingMenProportion': 19.7,
            'bingeDrinkingWomenProportion': 4.7,
            'abstainersPast12MonthsProportion': 61.0,
            'overallRank': 'joint 78th lightest',
            'overallConsumptionMen': 10.80,
            'overallConsumptionWomen': 0.80
        },
        'DEU': {
            'name': 'Germany',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [6.3248, 3.2804, 2.1948, 0.0],
            'overallConsumptionBothSexes': 11.80,
            'bingeDrinkingMenProportion': 21.3,
            'bingeDrinkingWomenProportion': 5.0,
            'abstainersPast12MonthsProportion': 19.7,
            'overallRank': '23rd heaviest',
            'overallConsumptionMen': 16.80,
            'overallConsumptionWomen': 7.00
        },
        'GMB': {
            'name': 'Gambia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.1904, 0.0238, 0.0102, 3.179],
            'overallConsumptionBothSexes': 3.40,
            'bingeDrinkingMenProportion': 1.3,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 89.0,
            'overallRank': '48th lightest',
            'overallConsumptionMen': 5.50,
            'overallConsumptionWomen': 1.40
        },
        'KAZ': {
            'name': 'Kazakhstan',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.2754, 0.3193, 6.7053, 0.0],
            'overallConsumptionBothSexes': 10.30,
            'bingeDrinkingMenProportion': 14.7,
            'bingeDrinkingWomenProportion': 1.3,
            'abstainersPast12MonthsProportion': 60.6,
            'overallRank': 'joint 36th heaviest',
            'overallConsumptionMen': 15.70,
            'overallConsumptionWomen': 5.50
        },
        'PHL': {
            'name': 'Philippines',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.4526, 0.0162, 3.9258, 0.0],
            'overallConsumptionBothSexes': 5.40,
            'bingeDrinkingMenProportion': 3.1,
            'bingeDrinkingWomenProportion': 0.2,
            'abstainersPast12MonthsProportion': 55.7,
            'overallRank': 'joint 73rd lightest',
            'overallConsumptionMen': 9.20,
            'overallConsumptionWomen': 1.70
        },
        'KGZ': {
            'name': 'Kyrgyzstan',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.9718, 0.1806, 3.1347, 0.0129],
            'overallConsumptionBothSexes': 4.30,
            'bingeDrinkingMenProportion': 14.5,
            'bingeDrinkingWomenProportion': 1.1,
            'abstainersPast12MonthsProportion': 61.8,
            'overallRank': 'joint 60th lightest',
            'overallConsumptionMen': 6.70,
            'overallConsumptionWomen': 2.00
        },
        'TTO': {
            'name': 'Trinidad and Tobago',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [3.618, 0.134, 2.9346, 0.0201],
            'overallConsumptionBothSexes': 6.70,
            'bingeDrinkingMenProportion': 30.7,
            'bingeDrinkingWomenProportion': 6.7,
            'abstainersPast12MonthsProportion': 48.9,
            'overallRank': 'joint 86th heaviest',
            'overallConsumptionMen': 9.70,
            'overallConsumptionWomen': 3.90
        },
        'LVA': {
            'name': 'Latvia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [5.7687, 1.3161, 4.551, 0.6642],
            'overallConsumptionBothSexes': 12.30,
            'bingeDrinkingMenProportion': 31.0,
            'bingeDrinkingWomenProportion': 12.9,
            'abstainersPast12MonthsProportion': 32.3,
            'overallRank': 'joint 15th heaviest',
            'overallConsumptionMen': 19.70,
            'overallConsumptionWomen': 6.30
        },
        'JPN': {
            'name': 'Japan',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.3824, 0.2952, 3.744, 1.7784],
            'overallConsumptionBothSexes': 7.20,
            'bingeDrinkingMenProportion': 30.0,
            'bingeDrinkingWomenProportion': 6.6,
            'abstainersPast12MonthsProportion': 31.1,
            'overallRank': 'joint 70th heaviest',
            'overallConsumptionMen': 10.40,
            'overallConsumptionWomen': 4.20
        },
        'HRV': {
            'name': 'Croatia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.819, 5.4656, 1.8788, 0.0244],
            'overallConsumptionBothSexes': 12.20,
            'bingeDrinkingMenProportion': 22.3,
            'bingeDrinkingWomenProportion': 1.5,
            'abstainersPast12MonthsProportion': 19.5,
            'overallRank': 'joint 18th heaviest',
            'overallConsumptionMen': 17.70,
            'overallConsumptionWomen': 7.10
        },
        'HND': {
            'name': 'Honduras',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.604, 0.044, 2.348, 0.0],
            'overallConsumptionBothSexes': 4.00,
            'bingeDrinkingMenProportion': 8.1,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 52.6,
            'overallRank': 'joint 56th lightest',
            'overallConsumptionMen': 5.70,
            'overallConsumptionWomen': 2.30
        },
        'MMR': {
            'name': 'Myanmar',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.5782, 0.0399, 0.0826, 0.0],
            'overallConsumptionBothSexes': 0.70,
            'bingeDrinkingMenProportion': 0.2,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 92.1,
            'overallRank': 'joint 11th lightest',
            'overallConsumptionMen': 1.40,
            'overallConsumptionWomen': 0.00
        },
        'GNQ': {
            'name': 'Equatorial Guinea',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.8348, 4.7652, 0.0, 0.0],
            'overallConsumptionBothSexes': 6.60,
            'bingeDrinkingMenProportion': 8.2,
            'bingeDrinkingWomenProportion': 0.9,
            'abstainersPast12MonthsProportion': 60.0,
            'overallRank': 'joint 86th lightest',
            'overallConsumptionMen': 10.10,
            'overallConsumptionWomen': 2.90
        },
        'TUN': {
            'name': 'Tunisia',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.029, 0.4155, 0.0555, 0.0],
            'overallConsumptionBothSexes': 1.50,
            'bingeDrinkingMenProportion': 0.1,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 94.3,
            'overallRank': 'joint 25th lightest',
            'overallConsumptionMen': 3.00,
            'overallConsumptionWomen': 0.00
        },
        'NIC': {
            'name': 'Nicaragua',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.94, 0.025, 3.03, 0.0],
            'overallConsumptionBothSexes': 5.00,
            'bingeDrinkingMenProportion': 23.3,
            'bingeDrinkingWomenProportion': 1.6,
            'abstainersPast12MonthsProportion': 50.7,
            'overallRank': '70th lightest',
            'overallConsumptionMen': 8.70,
            'overallConsumptionWomen': 1.50
        },
        'SGP': {
            'name': 'Singapore',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [1.402, 0.27, 0.294, 0.034],
            'overallConsumptionBothSexes': 2.00,
            'bingeDrinkingMenProportion': 8.1,
            'bingeDrinkingWomenProportion': 0.3,
            'abstainersPast12MonthsProportion': 50.1,
            'overallRank': 'joint 31st lightest',
            'overallConsumptionMen': 2.80,
            'overallConsumptionWomen': 1.20
        },
        'COM': {
            'name': 'Comoros',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.0466, 0.0444, 0.1092, 0.0],
            'overallConsumptionBothSexes': 0.20,
            'bingeDrinkingMenProportion': 1.7,
            'bingeDrinkingWomenProportion': 0.1,
            'abstainersPast12MonthsProportion': 88.1,
            'overallRank': 'joint second lightest',
            'overallConsumptionMen': 0.40,
            'overallConsumptionWomen': 0.10
        },
        'GBR': {
            'name': 'United Kingdom',
            'otherNames': ['UK', 'England', 'Wales', 'Scotland', 'Northern Ireland'],
            'ifNameNeedsAThePrefix': 'the ',
            'drinksData': [4.2804, 3.9208, 2.5288, 0.87],
            'overallConsumptionBothSexes': 11.60,
            'bingeDrinkingMenProportion': 37.2,
            'bingeDrinkingWomenProportion': 16.8,
            'abstainersPast12MonthsProportion': 16.1,
            'overallRank': 'joint 24th heaviest',
            'overallConsumptionMen': 16.50,
            'overallConsumptionWomen': 6.90
        },
        'GRC': {
            'name': 'Greece',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [2.8943, 4.8719, 2.4926, 0.0412],
            'overallConsumptionBothSexes': 10.30,
            'bingeDrinkingMenProportion': 48.2,
            'bingeDrinkingWomenProportion': 18.8,
            'abstainersPast12MonthsProportion': 33.8,
            'overallRank': 'joint 36th heaviest',
            'overallConsumptionMen': 14.60,
            'overallConsumptionWomen': 6.20
        },
        'PRY': {
            'name': 'Paraguay',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.4968, 1.6016, 2.5344, 0.176],
            'overallConsumptionBothSexes': 8.80,
            'bingeDrinkingMenProportion': 43.0,
            'bingeDrinkingWomenProportion': 17.3,
            'abstainersPast12MonthsProportion': 38.1,
            'overallRank': '52nd heaviest',
            'overallConsumptionMen': 12.40,
            'overallConsumptionWomen': 5.20
        },
        'TLS': {
            'name': 'Timor-Leste',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [0.0558, 0.4554, 0.0888, 0.0],
            'overallConsumptionBothSexes': 0.60,
            'bingeDrinkingMenProportion': 0.1,
            'bingeDrinkingWomenProportion': 0.0,
            'abstainersPast12MonthsProportion': 92.9,
            'overallRank': 'joint eighth lightest',
            'overallConsumptionMen': 1.00,
            'overallConsumptionWomen': 0.10
        },
        'BWA': {
            'name': 'Botswana',
            'ifNameNeedsAThePrefix': '',
            'drinksData': [4.704, 0.9912, 0.966, 1.7388],
            'overallConsumptionBothSexes': 8.40,
            'bingeDrinkingMenProportion': 11.6,
            'bingeDrinkingWomenProportion': 1.2,
            'abstainersPast12MonthsProportion': 58.5,
            'overallRank': 'joint 57th heaviest',
            'overallConsumptionMen': 14.30,
            'overallConsumptionWomen': 2.50
        }
    };
});